version: "{branch} {build}"

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.m2

install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0

build_script:
  - mvn clean test-compile

test_script:
  - mvn verify
